<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Hermes\Api\Client'                         => __DIR__ . '/src/Api/Client.php',
    'Hermes\Api\ClientFactory'                  => __DIR__ . '/src/Api/ClientFactory.php',
    'Hermes\Api\Response'                       => __DIR__ . '/src/Api/Response.php',
    'Hermes\Exception\ExceptionInterface'       => __DIR__ . '/src/Exception/ExceptionInterface.php',
    'Hermes\Exception\InvalidArgumentException' => __DIR__ . '/src/Exception/InvalidArgumentException.php',
    'Hermes\Exception\NotAvailableException'    => __DIR__ . '/src/Exception/NotAvailableException.php',
    'Hermes\Exception\RuntimeException'         => __DIR__ . '/src/Exception/RuntimeException.php',
    'Hermes\Module'                             => __DIR__ . '/src/Module.php',
    'Hermes\Paginator\ApiPaginator'             => __DIR__ . '/src/Paginator/ApiPaginator.php',
    'Hermes\Resource\Paginator'                 => __DIR__ . '/src/Resource/Paginator.php',
    'Hermes\Resource\Resource'                  => __DIR__ . '/src/Resource/Resource.php',
);
